<form action="<?= BASE_URL . 'login/' ?>" method="POST">
  <input type="hidden" name="action" value="log-in">
  <label for="user">
    Email: 
    <input type="text" name="email" required>
  </label>
  <label for="pass">
    Password: 
    <input type="password" name="pass" required>
  </label>

  <?php if (isset($wrongEmail)) { ?>
    <p>Wrong email</p>
  <?php } ?>

  <?php if (isset($wrongPass)) { ?>
    <p>Wrong password</p>
  <?php } ?>
  <button type="submit">Log in</button>
  <a href="<?= BASE_URL . 'register/' ?>">Don't have an account? Sing in.</a>
</form>