<form method="POST">
  <input type="hidden" name="id" value="<?= $creator->id ?? null ?>">  
  <label for="name">
    Name: 
    <input type="text" name="name" value="<?= $creator->name ?? null?>" required>
  </label>
  <label for="link">
    Profile link: 
    <input type="text" name="link" value="<?= $creator->profile_link ?? null?>" required>
  </label>

  <div class="submits">
    <?php if ($mode == 'edit') { ?> 
      <button type="submit" formaction="<?= BASE_URL . 'update/creator/' . $creator->id ?>">Save</button>
      <button type="submit" formaction="<?= BASE_URL . 'delete/creator/' . $creator->id ?>" class="delete">Delete</button>
    <?php } else { ?>
      <button type="submit" formaction="<?= BASE_URL . 'create/creator/' ?>">Add</button>
    <?php } ?>
  </div>
</form>