<form method="POST" enctype="multipart/form-data">
  <input type="hidden" name="id" value="<?= $game->id ?? null ?>">
  <label for="image"> 
    Image:
    <input type="file" name="image" accept=".jpg,.jpeg,.png,.gif">
  </label>
  <label for="name">
    Name: 
    <input type="text" name="name" value="<?= $game->name ?? null?>" required>
  </label>
  <label for="description">
    Description: 
    <input type="text" name="description" value="<?= $game->description ?? null?>" required>
  </label>

  <div class="submits">
  <?php if ($mode == 'edit') { ?> 
    <button type="submit" formaction="<?= BASE_URL . 'update/game/' . $game->id ?>">Save</button>
    <button type="submit" formaction="<?= BASE_URL . 'delete/game/' . $game->id ?>" class="delete">Delete</button>
  <?php } else { ?>
    <button type="submit" formaction="<?= BASE_URL . 'create/game/' ?>">Add</button>
  <?php } ?>
  </div>
</form>