<form method="POST">
  <input type="hidden" name="id" value="<?= $category->id ?? null ?>">
  <label for="game">
    Game: 
    <select name="game" id="game" required>
      <option value="" selected disabled>-</option>
      <?php foreach($games as $game) : ?>
        <option value="<?= $game->id?>"  
          <?= isset($category) ? ($category->id_game == $game->id ? 'selected' : '') : '' ?> >
          <?= $game->name ?>
        </option>
      <?php endforeach?>
    </select>
  </label>
  <label for="name">
    Name: 
    <input type="text" name="name" value="<?= $category->name ?? null?>" required>
  </label>

  <?php if ($mode == 'edit') { ?> 
    <button type="submit" formaction="<?= BASE_URL . 'admin/categories/' . $category->id ?>">Save</button>
    <button type="submit" formaction="<?= BASE_URL . 'admin/categories/delete/' . $category->id ?>">Delete</button>
  <?php } else { ?>
    <button type="submit" formaction="<?= BASE_URL . 'admin/categories/new' ?>">Add</button>
  <?php } ?>
</form>