<form method="POST" enctype="multipart/form-data">
  <input type="hidden" name="id" value="<?= $mod->id ?? null ?>">
  <input type="hidden" name="game" value="<?= $game->id ?>">
  <label for="image"> 
    Image:
    <input type="file" name="image" accept=".jpg,.jpeg,.png,.gif">
  </label>
  <label for="game">
    Game: 
    <input type="text" value="<?= $game->name ?>" disabled>
  </label>

  <label for="category">
    Category: 
    <select name="category" id="category" required>
      <option value="" selected disabled>-</option>
      <?php foreach($categories as $category) : ?>
        <option value="<?= $category->id?>"  
          <?= isset($mod) ? ($mod->category_id == $category->id ? 'selected' : '') : '' ?> >
          <?= $category->name ?>
        </option>
      <?php endforeach?>
    </select>
  </label>

  <label for="name">
    Name: 
    <input type="text" name="name" value="<?= $mod->name ?? null?>" required>
  </label>

  <label for="creator">
    Creator: 
    <select name="creator" id="creator" required>
      <option value="" selected disabled>-</option>
      <?php foreach($creators as $creator) : ?>
        <option value="<?= $creator->id?>"  
          <?= isset($mod) ? ($mod->creator_id == $creator->id ? 'selected' : '') : '' ?> >
          <?= $creator->name ?>
        </option>
      <?php endforeach?>
    </select>
  </label>

  <label for="description">
    Description: 
    <input type="text" name="description" value="<?= $mod->description ?? null?>" required>
  </label>

  <label for="creation_date">
    Creation date: 
    <input type="date" name="creation_date" value="<?= $mod->creation_date ?? null?>" required>
  </label>

  <label for="github_link">
    Github link: 
    <input type="text" name="github_link" value="<?= $mod->github_link ?? null?>" required>
  </label>

  <label for="download_link">
    Download link: 
    <input type="text" name="download_link" value="<?= $mod->download_link ?? null?>" required>
  </label>

  <?php if ($mode == 'edit') { ?> 
    <button type="submit" formaction="<?= BASE_URL . 'update/mod/' . $mod->id ?>">Save</button>
    <button type="submit" formaction="<?= BASE_URL . 'delete/mod/' . $mod->id ?>">Delete</button>
  <?php } else { ?>
    <button type="submit" formaction="<?= BASE_URL . 'create/mod/' ?>">Add</button>
  <?php } ?>
</form>