<form method="POST">
  <input type="hidden" name="id" value="<?= $category->id ?? null ?>">
  <input type="hidden" name="game" value="<?= $game->id?>">
  <label for="game">
    Game: 
    <input type="text" value="<?= $game->name?>" disabled >
  </label>
  <label for="name">
    Name: 
    <input type="text" name="name" value="<?= $category->name ?? null?>" required>
  </label>

  <?php if ($mode == 'edit') { ?> 
    <button type="submit" formaction="<?= BASE_URL . 'admin/category/' . $game->id . '/' . $category->id ?>">Save</button>
    <button type="submit" formaction="<?= BASE_URL . 'admin/category/delete/' . $category->id ?>">Delete</button>
  <?php } else { ?>
    <button type="submit" formaction="<?= BASE_URL . 'admin/category/' . $game->id . '/new' ?>">Add</button>
  <?php } ?>
</form>