<form method="POST">
  <label for="name">
    Name: 
    <input type="text" name="name" value="<?= $game->name?>" required>
  </label>
  <label for="description">
    Description: 
    <input type="text" name="description" value="<?= $game->description?>" required>
  </label>

  <button type="submit" formaction="<?= BASE_URL . 'admin/games/' . $game->id ?>">Save</button>
  <button type="submit" formaction="<?= BASE_URL . 'admin/games/delete/' . $game->id ?>">Delete</button>
</form>