<ul>
  <?php foreach($mods as $mod): ?>
    <li>
      <a href="<?= BASE_URL . 'modpage/' . $mod->id?>"><?= $mod->name ?></a>
      <?php if (isset($_SESSION['admin']) && $_SESSION['admin'] = 1) :?>
        <a href="<?= BASE_URL . 'admin/mods/' . $mod->id ?>">Edit</a>
      <?php endif ?>
    </li>
  <?php endforeach?>
  <?php if (isset($_SESSION['admin']) && $_SESSION['admin'] = 1) :?>
    <li>
        <a href="<?= BASE_URL . 'admin/mods/new' ?>">Add new mod</a>
    </li>
  <?php endif ?>
</ul>