<ul>
  <?php foreach($mods as $mod): ?>
    <li>
      <a href="<?= BASE_URL . 'modpage/' . $mod->id?>">
        <?php if (isset($mod->image) && !empty($mod->image)) : ?>
          <img src="<?= BASE_URL . $mod->image ?>" alt="<?= $mod->name ?> image">
        <?php endif ?>
        <?= $mod->name ?>
      </a>
      <?php if (isset($_SESSION['admin']) && $_SESSION['admin'] = 1) :?>
        <a href="<?= BASE_URL . 'edit/mod/' . $mod->game_id . '/' . $mod->id ?>">Edit</a>
      <?php endif ?>
    </li>
  <?php endforeach?>
  <?php if (isset($_SESSION['admin']) && $_SESSION['admin'] = 1) :?>
    <li>
        <a href="<?= BASE_URL . 'new/mod/' . $mod->game_id ?>">Add new mod</a>
    </li>
  <?php endif ?>
</ul>