<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?= isset($tittle) ? $tittle : 'Modlog' ?></title>
</head>
<body>
  <header>
    <h1><a href="<?= BASE_URL ?>">Modlog</a></h1>
    <h2><a href="<?= BASE_URL . 'creators '?>">Creators</a></h2>
    <h4>
      <?php if (isset($_SESSION['user_name'])) {?>
        <h4><?= $_SESSION['user_name'] ?></h4>
        <form action="<?= BASE_URL . 'login' ?>" method="POST">
          <input type="hidden" name="action" value="log-out">
          <input type="hidden" name="url" value="<?= "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>">
          <button type="submit">Log out</button>
        </form>
      <?php } else { ?>
        <a href="<?= BASE_URL . 'login'?>">Log in</a>
      <?php } ?>
    </h4>
  </header>