<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="<?= BASE_URL . 'public/css/index.css' ?>">
  <?php if(!empty($this->stylesheets)): 
    foreach($this->stylesheets as $stylesheet):?>
      <link rel="stylesheet" href="<?= $stylesheet ?>">
  <?php endforeach; endif;?>
  <title><?= isset($tittle) ? $tittle : 'Modlog' ?></title>
</head>
<body>
  <header>
    <div class="header-main">
      <h1><a href="<?= BASE_URL ?>">Modlog</a></h1>
      <?php if (isset($_SESSION['user_name'])) {?>
        <form action="<?= BASE_URL . 'logout' ?>" method="POST">
          <h4><?= $_SESSION['user_name'] ?></h4>
          <input type="hidden" name="url" value="<?= "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>">
          <button type="submit">Log out</button>
        </form>
      <?php } else { ?>
        <a href="<?= BASE_URL . 'login'?>">Log in</a>
      <?php } ?>
    </div>
    <nav>
      <ul>
        <li><a href="<?= BASE_URL ?>">Home</a></li>
        <li><a href="<?= BASE_URL . 'creators '?>">Creators</a></li>
      </ul>
    </nav>
  </header>
  <main>